name: Assign adamrybinski to New Issues
on:
  issues:
    types: [opened]
jobs:
  assign-adamrybinski:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: ['adamrybinski']
            });
