name: Assign Copilot to New Issues

on:
  issues:
    types: [opened]

jobs:
  assign-copilot:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Copilot
        uses: actions/github-script@v7
        with:
          script: |
            const copilotAssignee = 'copilot-swe-agent';
            await github.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [copilotAssignee]
            });
